// <auto-generated />
namespace ItemMaster.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReasonCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReasonCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201606130815576_ReasonCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
