//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPlan2015.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCardReport
    {
        public decimal CPLDTE { get; set; }
        public string SLSMN { get; set; }
        public string SMDESC { get; set; }
        public string PDTCDE { get; set; }
        public string PDTDES { get; set; }
        public string CUST { get; set; }
        public string CNAME { get; set; }
        public string CMGRP2 { get; set; }
        public string CMGRP3 { get; set; }
        public string CMGRP4 { get; set; }
        public string CADD2 { get; set; }
        public string ZCMTYP { get; set; }
        public decimal CPLUPD { get; set; }
        public decimal CPLUPT { get; set; }
    }
}
