//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPlan2015.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZGOVHOSP2
    {
        public string CUST { get; set; }
        public string CNAME { get; set; }
        public string CADD1 { get; set; }
        public string CMPHON { get; set; }
        public string CMCONT { get; set; }
        public string ARTRM { get; set; }
        public string SLSMN { get; set; }
        public string SMDESC { get; set; }
        public string PRNCPL { get; set; }
        public string ZCITYP { get; set; }
        public string ITEM { get; set; }
        public string IMDESC { get; set; }
        public Nullable<decimal> QUOTA { get; set; }
        public Nullable<decimal> NET_QTY { get; set; }
        public Nullable<System.DateTime> SYCTIME { get; set; }
        public Nullable<int> REM_QUOTA { get; set; }
    }
}
