//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPlan2015.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlvl
    {
        public string CMGRP2 { get; set; }
        public string CMGRP3 { get; set; }
        public string CMGRP4 { get; set; }
        public string ZCMTYP { get; set; }
        public long ZLVL1 { get; set; }
        public long ZLVL2 { get; set; }
        public Nullable<System.DateTime> SYCTIME { get; set; }
    }
}
