//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPlan2015.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class zsa756pf
    {
        public decimal CPLDTE { get; set; }
        public string SLSMN { get; set; }
        public string SMDESC { get; set; }
        public string PDTCDE { get; set; }
        public string PDTDES { get; set; }
        public decimal C_JNMAH { get; set; }
        public decimal C_JNMAR { get; set; }
        public decimal C_JNMAD { get; set; }
        public decimal C_JNMAQ { get; set; }
        public decimal C_JNMAF { get; set; }
        public decimal C_JNMAI { get; set; }
        public string CUST { get; set; }
        public string CNAME { get; set; }
        public string CMGRP2 { get; set; }
        public string CMGRP3 { get; set; }
        public string CMGRP4 { get; set; }
        public string CADD1 { get; set; }
        public string CADD2 { get; set; }
        public string ZCMTYP { get; set; }
        public decimal C_JNMAE { get; set; }
        public decimal C_JNMAO { get; set; }
        public decimal C_JNMAP { get; set; }
        public decimal C_JNMAG { get; set; }
        public string C_JNMAC { get; set; }
        public string C_JNMAK { get; set; }
        public string C_JNMAL { get; set; }
        public Nullable<System.DateTime> SYCTIME { get; set; }
    }
}
